export enum Commamnd {
    MainInit = "mainInit",
    EndChooseTicket = "endChooseTicket",
    EndChoosTrain = "endChoosTrain",
    ShowTeaching = "showTeaching",
    EndTeaching = "endTeaching",
    WaitSignalLight = "waitSignalLight",
    ShowVideo = "showVideo",
    CloseVideo = "closeVideo",
    ShowQA = "showQA",
    ShowAgainQA = "showAgainQA",
    EndQA = "endQA",
    ShowAnswer = "showAnswer",
    EndAnswer = "endAnswer",
    ShowExplain = "showExplain",
    EndExplain = "endExplain",
    ShowStationInfo = "showStationInfo",
    EndtationInfo = "endTationInfo",
    ShowGetProps = "showGetProps",
    EndGetProps = "endGetProps",

    CloseUrlView = "closeUrlView",
    ShowEndGame = "showEndGame",
    AgainGame = "againGame",
    GoLottery = "goLottery",
    DoorAgainGame = "doorAgainGame",
    MenGO = "menGo",
    ManSkip="manSkip",
    ManWait = "manWait",
    ManLineWait = "manLineWait",
    MoveTarget = "moveTarget",
    UpdataUIStart = "updataUIStart",
    ClinetClickStart_Stop = "clinetClickStart_Stop",
    ShowAllView = "showAllView",
    WebCheckData = "webCheckData",
    EndToBackGame= "endToBackGame"
}