export enum GameEvent {
    ControllPath ="Controll",
    ControllComponent ="Controll",
    SetModel = "SetModel",
    SendModel = "SendModel",
    SendCommand = "sendCommand",
    InitMap = "InitMap",
    ShowMessage = "ShowMessage",
    HideMessage = "HideMessage",
    ManGO = "ManGO",
    ManStop = "ManStop",
    ManWait = "ManWait",
    ManSkip = "ManSkip",
    SetManState = "SetManState",
    MoveToStation = "MoveToStation",
    MoveToManCamera = "MoveToManCamera",
    ShowAllView = "ShowAllView",
    OpenDoor = "OpenDoor",
    CloseDoor = "CloseDoor",
    BearSetModle = "BearSetModle",
    GetStation = "GetStation",
    UIGetStation="UIGetStation",

    UIReset="UIReset",


    StopCloud = "StopCloud",
    StartCloud = "StartCloud",
    DeletCloud = "DeletCloud",
    OpenBufer = "OpenBufer",
    CloseBufer = "CloseBufer",
}